### PR TITLE
Update condition for adding line numbers to source

### PR DESCRIPTION
**Pull request by EpicEric**
Also look for the `language-pony-full-source` class in each codeblock.

### CODE REVIEW

**Comment by mfelsche** [comment]
@EpicEric Can you also draft a new release of the mkdocs-theme with this change, so ponyc can pick it up? If not, I can do it.

**Comment by EpicEric** [comment]
Yep.

**Comment by SeanTAllen** [comment]
Wow. We still test with TravisCI for something. We should really change that  given that they either shut that down already or are soon.

**Comment by SeanTAllen** [comment]
I took a look at the travisci setup, I don't understand enough about python and node to craft a github actions replacement. I'll need to leave that to someone else.

**Comment by SeanTAllen** [comment]
@EpicEric @mfelsche can one of you do a release? thanks.

**Pull request merged**
